;;"selfset.scm" Set single letter identifiers to their symbols.
;@
 (define a 'a)
 (define b 'b)
 (define c 'c)
 (define d 'd)
 (define e 'e)
 (define f 'f)
 (define g 'g)
 (define h 'h)
 (define i 'i)
 (define j 'j)
 (define k 'k)
 (define l 'l)
 (define m 'm)
 (define n 'n)
 (define o 'o)
 (define p 'p)
 (define q 'q)
 (define r 'r)
 (define s 's)
 (define t 't)
 (define u 'u)
 (define v 'v)
 (define w 'w)
 (define x 'x)
 (define y 'y)
 (define z 'z)
